### ISSUE TITLE
[auto] - raydium integration ? 

### ISSUE THREAD

**Issue by cbastienbaron** [autofarm-network/autofarmV2#8]
Hey guys,

Thanks for auto farm, with this product, i'll become more and more lazy

it is also planned an integration with raydium / sol - https://raydium.io/?
I miss the autocompound on it :)

here news from sushi : https://forum.sushiswapclassic.org/t/codename-bonsai-proposal-for-building-out-sushiswap-on-solana-and-serum/2653

https://snapshot.org/#/sushi/proposal/QmSDwPmm9VTi9dHmg63tMWx1j7MButsRWEenCYQcT8ADL6

current apr $RAY : ~ 123%
current apr $RAY/uSDT : ~ S254%
current apr $COPE/uSDC : ~ S1266% :exploding_head: 
...

more info from https://raydium.io/fusion/

**Comment by autofarm-network** [comment]
Glad that you enjoy using our vaults! Thanks for the suggestion; for future feedback or suggestions, you can drop it in our Discord ideas channel here: https://discord.gg/avUw4CnzqQ

**Comment by cbastienbaron** [comment]
don't have discord and don't want to open it :) have a good day
